
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

ribbon: 
  IsSecure: false

logging:
  level:
    io:
      pivotal: DEBUG

spring:
  profile: dev
eureka:
  client:    
    serviceUrl:
      defaultZone: http://service-registry-puran.mybluemix.net # <-- substitute your service-registry url
