
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

ribbon: 
  IsSecure: false

logging:
  level:
    io:
      pivotal: DEBUG

spring:
  profile: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id}
spring:
  profile: dev
eureka:
  client:    
    serviceUrl:
      defaultZone: http://service-registry-puran.mybluemix.net # <-- substitute your service-registry url
