
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

ribbon: 
  IsSecure: false

logging:
  level:
    io:
      pivotal: DEBUG
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}

