---
spring:
  profile: cloud
  eureka:
    instance:
      hostname: ${vcap.application.uris[0]}
      nonSecurePort: 80
      metadataMap:
        instanceId: ${vcap.application.instance_id}
---
spring:
  profile: dev
  eureka:
    instance:
      hostname: ${vcap.application.uris[0]}
      nonSecurePort: 80
      metadataMap:
        instanceId: ${vcap.application.instance_id}
