
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

ribbon: 
  IsSecure: false

logging:
  level:
    io:
      pivotal: DEBUG
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id}
